version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:12-browsers
    steps:
    - checkout
    - run: npm ci
    - run: npm test

workflows:
  version: 2
  test:
    jobs:
      - test
